### ISSUE TITLE
Support specifying an install-config while deploying OCP Clusters

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/shipyard#1040]
Currently, we can deploy OCP Clusters on AWS/GCP using the Shipyard framework. It would be helpful if the toolset can support specifying a custom install-config yaml (which can be manually customised as necessary) to deploy the OCP clusters.

**Comment by sridhargaddam** [comment]
CC @mkolesnik

**Comment by mkolesnik** [comment]
If we want to support OVN/default switch this should be easy to do with existing CNI support in our settings.yaml [1], otherwise it could be more complicated.

WDYT @sridhargaddam 

[1] https://submariner.io/development/shipyard/settings/#deployment-settings-file

**Comment by dfarrell07** [comment]
Per discussions, we could change this to be more general and then bump the prio.
