### ISSUE TITLE
Scripting for parsing flaky failures in `Flake Finder` jobs

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#1141]
As a dev it would be nice to have some sort of CLI script/command to gather details from the `Flake Finder` jobs and parse them into more detailed data that can be drilled down:

* Which combination failed (eg globalnet, lighthouse, etc)
* Which specific tests failed
* Perhaps pod logs from the time of failure?

**Comment by dfarrell07** [comment]
Another option, with a different set of trade-offs, would be an ELK stack.

**Comment by dfarrell07** [comment]
This could also be helped by the issue to print test names, to make that more clear. We could also run this in post-mortem and raise issues on failures.
