### ISSUE TITLE
Update the dependencies of our custom GHAs, document

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#1227]
The release-images GHA hosted in Shipyard is using Docker's setup-qemu-builder 1.2.0, as shown by the node errors which were fixed in 2.0.0.

https://github.com/submariner-io/submariner-operator/actions/runs/4787228603
https://github.com/docker/setup-qemu-action/releases

This highlights that Dependabot doesn't keep these up-to-date for us. We should update these:

```
e2e/action.yaml:77:      uses: submariner-io/shipyard/gh-actions/restore-images@devel
release-images/action.yaml:17:      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
release-images/action.yaml:19:      uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
cache-images/action.yaml:14:      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
restore-images/action.yaml:18:      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
```

And add docs here:

https://submariner.io/development/building-testing/ci-maintenance/

**Comment by skitt** [comment]
Ah, nice catch!
