### ISSUE TITLE
Implement basic GH action

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#135]
A basic action is needed for any KIND deployment to work, since the default GH actions VMs don't have enough free space.

**Comment by skitt** [comment]
This is no longer an issue, is it @mkolesnik?

**Comment by mkimuram** [comment]
@mkolesnik

Does it make sense to split steps in gh-actions/e2e/action.yaml?
- Reclaim space
- Install WireGuard
- Run e2e test

In https://github.com/submariner-io/submariner/pull/1202 , it at least needs to reuse "Reclaim space" without "Run e2e test" to run different e2e test. 

If it is good to go, I will make a PR.

Note that nesting composite actions doesn't seem to be officially supported yet, but there's workaround. 
https://github.com/actions/runner/issues/646#issuecomment-790007107

**Comment by mkimuram** [comment]
Above `mithro/actions-includes` workaround seems to require pre-process action.yaml, which might not reduce complexity for a small duplicated code case. I will look into to apply @mangelajo 's [suggestion](https://github.com/submariner-io/submariner/pull/1202#discussion_r601524012).

We might be able to consider further improvement after Github supports nested composite actions.

**Comment by mkolesnik** [comment]
> @mkolesnik
> 
> Does it make sense to split steps in gh-actions/e2e/action.yaml?
> 
>     * Reclaim space
> 
>     * Install WireGuard
> 
>     * Run e2e test
> 

We already discussed this previously and decided these are internal implementation details of running E2E, so splitting them won't be a good idea for now (until GH shared ctions support calling other shared actions)

> 
> In [submariner-io/submariner#1202](https://github.com/submariner-io/submariner/pull/1202) , it at least needs to reuse "Reclaim space" without "Run e2e test" to run different e2e test.
> 
> If it is good to go, I will make a PR.
> 
> Note that nesting composite actions doesn't seem to be officially supported yet, but there's workaround.
> [actions/runner#646 (comment)](https://github.com/actions/runner/issues/646#issuecomment-790007107)

We can wait for official support

**Comment by mkolesnik** [comment]
> This is no longer an issue, is it @mkolesnik?

Yes I'm closing this as we already did it
