### ISSUE TITLE
Move version script fix to shipyard repo.

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/shipyard#144]
This issue is to keep track of the task of moving  https://github.com/submariner-io/lighthouse/pull/124 to Shipyard  if that is better. If not this shall be closed.

**Comment by mangelajo** [comment]
In general I think we have a plan to use the image release scripts from shipyard also.

**Comment by mkolesnik** [comment]
This was fixed by https://github.com/submariner-io/lighthouse/pull/127
