### ISSUE TITLE
Lighthouse now requires a ServiceExport

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/shipyard#182]
Without that ServiceExport, submariner-operator which smoke-tests the
discovery of the IP will fail.

Related-commit: https://github.com/submariner-io/lighthouse/commit/c3bac6af3358ded33c47b63bb9ff1e269820a062

**Comment by vthapar** [comment]
Added to Lighthouse E2E by https://github.com/submariner-io/lighthouse/pull/137

**Comment by tpantelis** [comment]
It seems this was addressed.
