### ISSUE TITLE
-dp-context of E2E has different orders across projects

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/shipyard#184]
**Shipyard** adds -dp-context cluster1 -dp-context cluster2 -dp-context cluster3, such order is used by **Lighthouse**.

 **Submariner** uses -dp-context cluster2 -dp-context cluster3 -dp-context cluster1

**Subctl** consumes e2e providing only two dp contexts.

We need to make them uniform so : 
    * The shipyard e2e script will work for all
    * Subctl can consume all uniformly.

I created this, but probably the best option is to make them all uniform the way shipyard includes them today, which makes more sense.

This needs to be thought.

https://github.com/submariner-io/lighthouse/pull/151

**Comment by tpantelis** [comment]
This was fixed by passing the contexts on the command line.
