### ISSUE TITLE
D/S CI collect K8 logs for debugging failed tests

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/shipyard#280]
we need to add a feature to record and collect cluster/aplications pod logs and save them in files , to be displayed when we click on a job in jenkins
example : 
how would we know what went wrong below??
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/783/Test-Report/

**Comment by pinikomarov** [comment]
@manosnoam   what do you think ?

**Comment by manosnoam** [comment]
Indeed this is what the last step does - "Collecting Submariner pods logs due to test failure"

Can you see if that's good enough ?

**Comment by pinikomarov** [comment]
closed
