### ISSUE TITLE
Run subctl benchmark as part of OSP-AWS tests

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/shipyard#336]
In order to test subctl benchmark feature, we will follow the documentation: https://github.com/submariner-io/submariner-website/pull/274/files
And execute it on our OSP-AWS (Jenkins downstream) environment.

Originally posted by @manosnoam in https://github.com/submariner-io/submariner-operator/issue_comments/697210490

**Comment by nyechiel** [comment]
@manosnoam @pinikomarov are you looking into this one? I am not sure what exactly you want to track in this Issue

**Comment by manosnoam** [comment]
@nyechiel I'm closing this issue, as we're planning to implement it internally.
If we'll find requirements for Benchmark results, we'll open relevant issue here.
