### ISSUE TITLE
D/S CI - add action to collect all cluster logs after job has failures

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/shipyard#381]
after a job is finished , we need to collect some basic cluster 
logs , otherwise when the env is deleted we have no way to compare underlying issues of subsequent failures.

This should be added in: 
https://github.com/manosnoam/ocp-multi-cluster-tester

**Comment by pinikomarov** [comment]
@manosnoam @mkolesnik  any thoughts here ? 
Do we have or do you know a similar tool / framework ?

**Comment by manosnoam** [comment]
Hi @pinikomarov 
There a mechanism to collect pod logs, subctl info and more, see for example the last test report:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/38/Test-Report/
(Under "Collecting Submariner pods logs due to test failure" )

**Comment by pinikomarov** [comment]
@manosnoam I went over the logs collected there in the Collecting Submariner pods logs due to test failure section.
it's not very in-depth , it does give you a picture of what's going on right now but not a wide enough picture.
While it may be enough in some cases , ideally I would love to have: 
/var/log/* logs, security , system and more...
like ; sudo sosreport --all-logs --batch --tmp-dir=/var ...

**Comment by pinikomarov** [comment]
The way I see it , if I have a failure I would like to be able to search for that failure in past CI runs, and now I feel that some log data is hidden in past jobs..
@manosnoam also , do we have ssh into the cluster nodes ? - not sure myslf to be honest..

**Comment by pinikomarov** [comment]
@manosnoam , This is an example of data I've been missing , and that more log files 

https://github.com/submariner-io/submariner/issues/1019#issuecomment-742508716
and maybe additional debug config printouts may be beneficial : 

Suggestions:
- add debug info about SG/ACL rules of the cluster
- addmore lines of code to the logs : currently 500 
function print_pod_logs_in_namespace() {
[...]
      ${OC} -n $namespace logs $pod --timestamps --tail=500 || :

**Comment by pinikomarov** [comment]
This is  too broad , I'll reopen with a more specific implementation i if needed
