### ISSUE TITLE
Build the ovn-daemonset images

### ISSUE THREAD

**Issue by skitt** [submariner-io/shipyard#415]
Currently we use a hand-built image, `quay.io/vthapar/ovn-daemonset-f`, with a specific `docker pull` in `clusters.sh`; we need to build the image ourselves automatically instead.

**Comment by vthapar** [comment]
@skitt We need to add it to https://github.com/submariner-io/ovn-kubernetes and release from there. This image will rarely change, so no point doing a build in shipyard CI.

**Comment by skitt** [comment]
> @skitt We need to add it to https://github.com/submariner-io/ovn-kubernetes and release from there. This image will rarely change, so no point doing a build in shipyard CI.

Even if it doesn’t change much, we still need to be able to rebuild it (in Shipyard or elsewhere). An image which can’t be built automatically is unsupportable. It doesn’t have to be built all the time, but we do need to be able to rebuild it when necessary.
