### ISSUE TITLE
Subctl's version reports as `subctl-devel-1-g...`

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#424]
This is due to version calculation done in Shipyard, and since we changed the devel tag in operator it's now a bit broken.
The impact seems to be quite low.

We can fix this (either have it "proper" version, or just "devel" or something, if this issue has enough priority.

**Comment by manosnoam** [comment]
It is very useful for my CI to determine the major version which then I expect to lookup in OCP registry, for the join override command.
For example:
```
subctl version
subctl version: subctl-devel-1-g88ab629
```
It used to show 0.8.0 instead of "1" until recently, so CI downloaded the 0.8.0 image accordingly.

**Comment by skitt** [comment]
This would still be nice to fix.

**Comment by nyechiel** [comment]
@mkolesnik there have been a few changes in this area lately, is this one still relevant?

**Comment by mkolesnik** [comment]
```
$ curl -Ls https://get.submariner.io | VERSION=devel bash
Installing subctl version devel
  OS detected:           linux
  Architecture detected: amd64
  Download URL:          https://github.com/submariner-io/submariner-operator/releases/download/subctl-devel/subctl-devel-linux-amd64.tar.xz

Downloading...
subctl-devel-linux-amd64 has been installed as /home/mkolesni/.local/bin/subctl
This provides subctl version: devel
```

```
$ curl -Ls https://get.submariner.io | VERSION=0.9.0 bash
Installing subctl version v0.9.0
  OS detected:           linux
  Architecture detected: amd64
  Download URL:          https://github.com/submariner-io/releases/releases/download/v0.9.0/subctl-v0.9.0-linux-amd64.tar.xz

Downloading...
subctl-v0.9.0-linux-amd64 has been installed as /home/mkolesni/.local/bin/subctl
This provides subctl version: v0.9.0
```

Seems fine to me, closing for now unless there are any objections
