### ISSUE TITLE
Add make target for running MD link checks

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#427]
Support running markdown-link-check locally, from the shared dev container. We currently use a [GHA wrapping the CLI](https://github.com/gaurav-nelson/github-action-markdown-link-check), but we should be able to swap to the [raw CLI](https://github.com/tcort/markdown-link-check) pretty easily.

`find . -name \*.md -exec markdown-link-check {} \;`

This came out of discussions on the Automation Sync last week.

**Comment by skitt** [comment]
This is still relevant.

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
If there was a "prio:are-we-sure-we-want-this" label, I'd add it to this Issue.

I think it's not really that helpful to have the ability to run MD link checks locally for Shipyard projects, as they typically don't have a lot of docs (the website does, but would still need to use the third-party GHA). If you're adding docs with a link, it's easy enough to copy it to a browser locally, and it will still be verified on the PR and periodically.

There are pluses/minuses on both sides of maintaining a pin to releases of a popular third-party GHA dependency vs maintaining installs of the same underlying CLI tool and running it ourselves.

**Comment by mkolesnik** [comment]
I think we can close for now, and if theres still desire to do this it can be reopened
