### ISSUE TITLE
Add linter to verify no "Apply suggestions from code review" commits

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#439]
Commits generated as a part of the code review process, that should be squashed with the main PR commits, continue to sneak past (trying hard and much appreciated!) committers and get merged. Find a linter or create a check to verify commits with common strings like "Apply suggestions from code review" aren't merged.

**Comment by dfarrell07** [comment]
This tool might be a good option: https://github.com/marketplace/actions/commit-message-checker-for-pull-request

**Comment by dfarrell07** [comment]
Or, even better: https://github.com/tim-actions/wip-check

**Comment by skitt** [comment]
We still want this.

**Comment by dfarrell07** [comment]
Implemented this in https://github.com/submariner-io/submariner/pull/1439, will wait on review before sending it to other repos.

**Comment by dfarrell07** [comment]
Sent PRs to all the other repos:

https://github.com/submariner-io/submariner-operator/pull/1462
https://github.com/submariner-io/admiral/pull/244
https://github.com/submariner-io/cloud-prepare/pull/61
https://github.com/submariner-io/coastguard/pull/35
https://github.com/submariner-io/enhancements/pull/32
https://github.com/submariner-io/lighthouse/pull/575
https://github.com/submariner-io/releases/pull/174
https://github.com/submariner-io/shipyard/pull/591
https://github.com/submariner-io/submariner-charts/pull/154
https://github.com/submariner-io/submariner-website/pull/547

**Comment by dfarrell07** [comment]
All PRs are merged, thanks for all the reviews @skitt and @nyechiel. :pray:
