### ISSUE TITLE
Fix polarion not reporting of Ginkgo tests junit output

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/shipyard#48]
We want to import the Junit.xml results that is being generated from E2E tests, into Polarion.
There's a bug in JUMP polarion script, that fails to parse test messages (<system-ouput>) into Polarion.

The required solution is in 2 phases:

Phase 1: Create a temporary workaround to modify the XML file, to be able to be read by JUMP tool - This can be done in Python or in Bash.

Phase 2:  A complete resolution in the Ginkgo Test framework (GO) - to create the "<system-ouput>" under "<pass>" section as PR (pull request).
This requires experience in the Ginkgo framework, to fix + add unit-tests (not related to Submariner), to verify the PR , and approval by the community.

Please go over the ticket, and try to reproduce the issue. Once reproduced, you can start fixing it.

**Comment by pinikomarov** [comment]
@manosnoam I'm having troubles reproducing this even without the non imported tag : 
I've posted a message to the jump guys , describing my current block: 
[](https://projects.engineering.redhat.com/browse/RHOSINFRA-2701?focusedCommentId=2250304&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2250304
)
->
Let's see If they can help me out ...

> I'm trying for a reproducer here,
> trying to see if I switch passed-> system-out tags , the polarion test run will work...
> 
> #steps taken:
> 
> upload a to a test run results :
> http://pastebin.test.redhat.com/848072
> to a test test run on polarion :
> https://polarion.engineering.redhat.com/polarion/#/project/RHELOpenStackPlatform?shortcut=favorites%2FTest%20Runs
> 
> using jump cli :
> http://pastebin.test.redhat.com/848075
> 
> to this test test run :
> https://polarion.engineering.redhat.com/polarion/#/project/RHELOpenStackPlatform/testrun?id=20200325%2D0855
> 
> the upload is logged as succesfull :
> https://polarion.engineering.redhat.com/polarion/import/xunit-log?jobId=922333
> 
> but the test run is not updated with results
> 
> So is this a bug ?

**Comment by pinikomarov** [comment]
adding jira for tracking here : 
https://projects.engineering.redhat.com/browse/RHOSINFRA-2701
status is blocked at the moment

**Comment by pinikomarov** [comment]
@manosnoam hey I'm moving this issue here , since it's probably an error on our side, and the jira ticket is unreadable since it's been changed so much.

SO.. leyt's start over :) 

Where are the jobs that should report to polarion  ,  can you link them here ?

**Comment by manosnoam** [comment]
@pinikomarov  the [CI job](https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/645/consoleFull) that will use Polarion is the "Phase 3". But first we need to start with Phase 1 & 2.

This is the command to run (just an example) to import junit results to Polarion:
```
python jump.py --testrun-id=20190815-0853 --xml-file=e2e_junit_result.xml --update_testcases=True --debug=True
...
DEBUG   Writing polarion-testcase-id: RHELOSP-56278
DEBUG   Writing polarion-testcase-id: RHELOSP-56277
DEBUG   Writing polarion-testcase-id: RHELOSP-56279
```
 
However, looking at the Polarion test run [20190815-0853](https://polarion.engineering.redhat.com/polarion/#/project/RHELOpenStackPlatform/testrun?id=20190815-0853), it shows 0 tests run completed.

Attaching [e2e_junit_result.xml.zip](https://github.com/submariner-io/shipyard/files/4850396/e2e_junit_result.xml.zip) (extract before import).

**Comment by pinikomarov** [comment]
@manosnoam actually the error is : 
23:30:21 Starting CI Polarion XUnit Importer - 2020-07-07 11-30-21
23:30:52 ERROR: Invalid import file: Project id not specified or invalid.
23:30:52 ERROR: Unable to post result XML for '/home/jenkins/workspace/Submariner-OSP-AWS/junit_setup_subm.xml'.
23:30:52 Ending CI Polarion XUnit Importer - 2020-07-07 11-30-52

So we are missing a whole section of <properties/> in the junit_setup_subm.xml file.

at : 

![image](https://user-images.githubusercontent.com/33867702/86841751-fffe8680-c0ac-11ea-8358-51fc7b4a0153.png)

it should look like this : 
![image](https://user-images.githubusercontent.com/33867702/86842072-5966b580-c0ad-11ea-8bd7-a78417051023.png)

Question is , where do we add the properties to the junit.xml ?

**Comment by pinikomarov** [comment]
This uploads to polarion:

<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite failures="1" assertions="" name="setup_subm" tests="1" errors="1" time="0.0843582">
    <testcase assertions="1" name="print_test_plan" time="0.0843582" classname="setup_subm">
    </testcase>
    <testcase assertions="1" name="test_kubeconfig_aws_cluster_a" time="7.90006" classname="setup_subm">
    </testcase>
    </testsuite>
</testsuites>


![image](https://user-images.githubusercontent.com/33867702/86846744-f9274200-c0b3-11ea-8cd0-8f5f95e19166.png)

**Comment by pinikomarov** [comment]
This also uploads : 

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite failures="1" assertions="" name="setup_subm" tests="1" errors="1" time="0.0843582">
    <testcase assertions="1" name="print_test_plan" time="0.0843582" classname="setup_subm">
    <system-out><![CDATA[
+++ Running case: setup_subm.print_test_plan 
+++ working dir: /home/jenkins/workspace/Submariner-OSP-AWS
+++ command: print_test_plan
|     - test_submariner_e2e_with_go
|     - test_submariner_e2e_with_subctl
|     
+++ exit code: 0]]></system-out>
    </testcase>
    <testcase assertions="1" name="test_kubeconfig_aws_cluster_a" time="7.90006" classname="setup_subm">
    </testcase>
    </testsuite>
</testsuites>
```

**Comment by pinikomarov** [comment]
But when I try to upload the whole file : 
I get an error because of the non standard characters:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 789-790: ordinal not in range(128)

| 🎩︎[2020-07-07 23:23:29]

**Comment by pinikomarov** [comment]
@manosnoam I think this will solve the problem : 

https://github.com/pinikomarov/ocp-multi-cluster-tester/pull/1

**Comment by manosnoam** [comment]
> @manosnoam I think this will solve the problem :
> 
> [pinikomarov/ocp-multi-cluster-tester#1](https://github.com/pinikomarov/ocp-multi-cluster-tester/pull/1)

This is a **different Junit file** - which is being generated from my system tests in ocp-multicluster-tester.
It is recognize by Jenkins Polarion Plugin (but I did not yet try to import it).

The issue we're dealing here, is for **E2E Ginkgo results file**. We will have to fix it in Ginkgo project.

**Comment by pinikomarov** [comment]
@manosnoam so this actually loads into polarionafter the fix

**Comment by pinikomarov** [comment]
@manosnoam so the  e2e_junit_result.xml.zip file , how is it sent to polarion -> using jump ? 
where in the job is step where we send the job ? and where can I see that command ?

**Comment by pinikomarov** [comment]
@manosnoam tested and verified : 
to upload ginkgo tests to polarion you have to do : 
sed -i 's/passed/system-out/g'  e2e_junit_result.xml

how can I apply this fix ? 
seems jump  is not used ? ..
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/58a3a0888fda52167fd971bc595cedd947c17990/helper_functions#L680

**Comment by pinikomarov** [comment]
@manosnoam this should fix the polarion jump upload : 

https://github.com/pinikomarov/ocp-multi-cluster-tester/pull/1

**Comment by pinikomarov** [comment]
@manosnoam updated the pull request as per our recent talk: 

https://github.com/manosnoam/ocp-multi-cluster-tester/pull/1

**Comment by pinikomarov** [comment]
@manosnoam now we have to solve the next problem : 
Post action: 
09:12:25 Starting CI Polarion XUnit Importer - 2020-07-26 09-12-25
09:12:56 ERROR: Invalid import file: Project id not specified or invalid.

The use of xpolarion exporter .. is it necessary  ? 

We could just use jump tool no ? it's proven to work and it add the 
polarion test case id automatically..

a quick start guide is here: 
https://code.engineering.redhat.com/gerrit/gitweb?p=jump.git;a=blob;f=README.md;h=63ae2a90d658365c640a355e7dc1f0f030874669;hb=HEAD

we could implement it via a shell script function..

**Comment by pinikomarov** [comment]
@manosnoam I'm seeing this : 

https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/blue/organizations/jenkins/Submariner-OSP-AWS/detail/Submariner-OSP-AWS/779/pipeline

Archiving artifacts

Starting CI Polarion XUnit Importer - 2020-08-10 08-54-44

ERROR: Invalid import file: Unable to parse XML file.

Error: Line 3: cvc-complex-type.2.4.a: Invalid content was found starting with element 'passed'. One of '{skipped, error, failure, system-out, system-err, properties}' is expected.

Error: Line 36: cvc-complex-type.2.4.a: Invalid content was found starting with element 'passed'. One of '{skipped, error, failure, system-out, system-err, properties}' is expected.

Error: Line 66: cvc-complex-type.2.4.a: Invalid content was found starting with element 'passed'. One of '{skipped, error, failure, system-out, system-err, properties}' is expected.

Error: Line 1169: cvc-complex-type.2.4.a: Invalid content was found starting with element 'passed'. One of '{skipped, error, failure, system-out, system-err, properties}' is expected.

Error: Line 1202: cvc-complex-type.2.4.a: Invalid content was found starting with element 'passed'. One of '{skipped, error, failure, system-out, system-err, properties}' is expected.

Error: Line 1230: cvc-complex-type.2.4.a: Invalid content was found starting with element 'passed'. One of '{skipped, error, failure, system-out, system-err, properties}' is expected.

ERROR: Unable to post result XML for '/home/jenkins/workspace/Submariner-OSP-AWS/subm_e2e_junit.xml'.

ERROR: Invalid import file: Project id not specified or invalid.

ERROR: Unable to post result XML for '/home/jenkins/workspace/Submariner-OSP-AWS/subm_pkg_junit.xml'.

ERROR: Invalid import file: Project id not specified or invalid.

ERROR: Unable to post result XML for '/home/jenkins/workspace/Submariner-OSP-AWS/setup_subm_junit.xml'.

Ending CI Polarion XUnit Importer - 2020-08-10 08-56-15

**Comment by pinikomarov** [comment]
@manosnoam  so IMHO we should start fixing this by adding a : 
sed -i 's/passed/system-out/g' on all xmls  : 
i.e. : '
sed -i s/passed/system-out/g' $WORKDIR/*junit*.xml 
at this location :
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/20b700eeeb9b0ca7c0bc42bb656ec18a771108dc/setup_subm.sh#L2596

**Comment by manosnoam** [comment]
Yes, this is already done here:
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/20b700eeeb9b0ca7c0bc42bb656ec18a771108dc/setup_subm.sh#L2315

But it is beeing called just when using --polarion option:
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/20b700eeeb9b0ca7c0bc42bb656ec18a771108dc/setup_subm.sh#L74

I will create a Polarion test-case, and will try to upload the xmls.

**Comment by manosnoam** [comment]
It is now resolved, we can now use `--polarion` to import junit into Polarion server, and create test cases and results. For example:
https://polarion.engineering.redhat.com/polarion/#/project/OSE/testrun?id=20200911-1421&tab=records
