### ISSUE TITLE
Changes to Makefile.dapper can’t be tested in consuming projects

### ISSUE THREAD

**Issue by skitt** [submariner-io/shipyard#491]
When a Shipyard PR changes `Makefile.dapper`, it can be useful to run e2e in consuming projects; but the latter downloads the current `devel` `Makefile.dapper`, not the one to be tested (this was already a problem before projects were changed to download `Makefile.dapper`).

Ideally we should be able to override the downloaded `Makefile.dapper`, if only by copying the new version in — since it’s handled by a `Makefile` target, it shouldn’t be downloaded if it’s already present.

**Comment by tpantelis** [comment]
bump
