### ISSUE TITLE
Remove script specific Makefile variables

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#527]
There were some script specific Makefile variables added recently:

https://github.com/submariner-io/shipyard/blob/devel/Makefile.inc#L54-L69

We have, long ago, decided against having script specific make variables. In this regard, this change is a regression.
In addition, having these script options redefined as make variables, whereas other options aren't, is very inconsistent.

Instead of having and using these script specific variables, use the general `*_ARGS` variables i.e. `E2E_ARGS`

**Comment by dfarrell07** [comment]
Is this still going to be worked on?

**Comment by mkolesnik** [comment]
This has very low priority, closing for now
