### ISSUE TITLE
Improve OVN scripts to deploy on top of existing kind infrastructure

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/shipyard#544]
Our current OVN implementation has some flaws:

1) It's not following upstream changes to OVN, because we use an image we built ourselves,
2) We use scripts from ovn repo that deploy both Kind and OVN

To match the support of other cnis we would need to 
* [ ] Contribute to the upstream ovn-kubernetes the generation of images that we can consume, from their master , and/or releases later.
* [ ] Contribute to the upstream ovn-kubernetes repo scripts that can be used on top of kind to deploy ovn, without the need to use their monolitic kind+ovn
* [ ] Integrate such work into shipyard, so it's just another cni plugin.

**Comment by skitt** [comment]
We also rely on a very specific version of the OVN package in our container images.

**Comment by mangelajo** [comment]
> We also rely on a very specific version of the OVN package in our container images.

Yeah, that's what I want to fix with the 1st point: "Contribute to the upstream ovn-kubernetes the generation of images that we can consume, from their master , and/or releases later."

**Comment by skitt** [comment]
> > We also rely on a very specific version of the OVN package in our container images.
> 
> Yeah, that's what I want to fix with the 1st point: "Contribute to the upstream ovn-kubernetes the generation of images that we can consume, from their master , and/or releases later."

Even for `networkplugin-syncer`?

**Comment by mangelajo** [comment]
> > > We also rely on a very specific version of the OVN package in our container images.
> > 
> > 
> > Yeah, that's what I want to fix with the 1st point: "Contribute to the upstream ovn-kubernetes the generation of images that we can consume, from their master , and/or releases later."
> 
> Even for `networkplugin-syncer`?

Ah, for networkplugin-syncer the plan is to move completely to the go libraries (fixing the libraries first), so we can simply have an scratch image.

**Comment by tpantelis** [comment]
bump
