### ISSUE TITLE
Dapper base image is creeping back up (currently passed 1GB)

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#556]
It seems that especially the F34 bump added upwards of 120MB to the (uncompressed) image size. The compressed size went up by around 40MB.

Last image that used F33:
`quay.io/submariner/shipyard-dapper-base   devel-6118112       296cf762784a        5 days ago          879MB`

Current image based off F34:
`quay.io/submariner/shipyard-dapper-base   devel               8cea7a6a9dc8        3 days ago          1.01GB`

While not a huge issue, with dev environments being on laptops with (potentially) scarce storage, these bumps do matter. 
Also considering not everyone has fast internet connections, the bigger the image to pull the more time is wasted.

**Comment by dfarrell07** [comment]
This is more of a general thing we should watch out for than a particular issue we need to fix now. We should keep watching out for this, but close this per discussion on PR sync.
