### ISSUE TITLE
Cluster deploys on stable branches hang for 15m at clusters.sh/kind_fixup_config `docker inspect`

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#607]
When doing backports on the submariner-operator repo, all E2E jobs time out because there is a strange 15m delay that causes them to exceed their 30m timer. The delay shows up in logs like this:

```
2021-07-21T14:08:55.6914479Z [36m[submariner-operator]$ [cluster1] kind_fixup_config[0m
2021-07-21T14:08:55.6916126Z [36m[submariner-operator]$ [cluster1] docker inspect -f {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} cluster1-control-plane[0m
2021-07-21T14:08:55.6917620Z [36m[submariner-operator]$ [cluster1] head -n 1[0m
2021-07-21T14:23:58.0355141Z [36m[submariner-operator]$ [cluster1] sed -i -- s/server: .*/server: https:\/\/172.18.0.5:6443/g /go/src/github.com/submariner-io/submariner-operator/output/kubeconfigs/kind-config-cluster1[0m
```

Notice the 15m jump in the timestamps after the `docker inspect ... | head` line.

This is the relevant code in `clusters.sh`:

```
function kind_fixup_config() {
    local master_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${cluster}-control-plane | head -n 1)
    sed -i -- "s/server: .*/server: https:\/\/$master_ip:6443/g" $KUBECONFIG
```

It's identical to the [first `docker inspect` example in the main Docker docs](https://docs.docker.com/engine/reference/commandline/inspect/#get-an-instances-ip-address), so I suspect the code is fine.

Debugging notes:

- [ ] Can this be replicated in Shipyard, in the shared scripts tests?
  - Answer: Not currently, because other things are broken on shipyard 0.9 branch: https://github.com/dfarrell07/shipyard/pull/24
- [ ] Does this happen for all non-devel branches, or only the stable branches we've tried to backport to?
  - Tested here: https://github.com/dfarrell07/submariner-operator/pull/5 It seems CI itself doesn't have an issue with PRs to a non-devel branch (equal to devel) from another branch (devel+test commit).
- [ ] Is it possible to recreate this locally?

**Comment by dfarrell07** [comment]
It seems like basically all of the Shipyard 0.9 branch jobs are failing, but not with this error.

https://github.com/dfarrell07/shipyard/pull/24/checks?check_run_id=3126309304

I think this shows we really need periodic tests for stable branches.

**Comment by dfarrell07** [comment]
> I think this shows we really need periodic tests for stable branches.

The best way for this to work, just reacting to on.schedule GHA triggers from non-default branches, doesn't seem possible currently. 

https://github.community/t/scheduled-builds-of-non-default-branch/16306

But if we assume the GHA test logic is the same for devel and stable branches, then we can check out the stable branch repo and run scheduled tests like:

https://github.community/t/scheduled-builds-of-non-default-branch/16306/13

**Comment by dfarrell07** [comment]
I'm experimenting with E2E tests for stable branches in Shipyard and submariner-operator, but both attempts are failing (with different errors than this one):

https://github.com/dfarrell07/submariner-operator/pull/4
https://github.com/dfarrell07/shipyard/pull/25

**Comment by SteveMattar** [comment]
I tried to split the pipe between `docker inspect` and the `head` commands in this PR
https://github.com/SteveMattar/submariner-operator/pull/1
and then it hangs during the installation of the **weave cni** 
```
kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=v1.20.2&env.IPALLOC_RANGE=10.1.0.0/16
```

**Comment by SteveMattar** [comment]
Bumping kind to 0.11.1 will support k8s v1.20 and fix the e2e failures

**Comment by dfarrell07** [comment]
I think/hope this will be fixed by https://github.com/submariner-io/shipyard/pull/615.
