### ISSUE TITLE
Dapper-based builds should support local replaces

### ISSUE THREAD

**Issue by skitt** [submariner-io/shipyard#644]
It’s often convenient, when working on changes across repositories, to use local `replaces` in `go.mod`. Unfortunately this fails when building with Dapper since we only copy the current project into the build container. Such builds should support local replaces by also copying other projects as needed.

There is a workaround: run `go mod vendor` before the build.

**Comment by r2dedios** [comment]
Hi @skitt 
I have the following error when I run `go mod vendor`. I'm on `devel` branch.
```
go mod vendor
verifying github.com/mikefarah/yaml/v2@v2.4.0/go.mod: checksum mismatch
        downloaded: h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ=
        go.sum:     h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
I have tried clearing the cache and building it again, but the error persists.

**Comment by skitt** [comment]
@r2dedios unfortunately that’s not something we can do much about, until the dependency drops out of our tree (which doesn’t seem likely in the near future). You can work around the failure by deleting the corresponding line in `go.sum`:

    sed -i '/h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU=/d' go.sum

**Comment by r2dedios** [comment]
I see. But this does not cause other dependencies to renew well, does it?

**Comment by skitt** [comment]
> I see. But this does not cause other dependencies to renew well, does it?

Sorry, I don’t understand what you mean by “renew well”. The underlying problem is that the 2.4.0 tag in `mikefarah/yaml` was moved, and there are two different versions of the 2.4.0 artifacts — in particular, goproxy has a different version compared to what is currently exposed by the upstream repository. So depending on where your system downloads its dependencies from, you’ll get a different hash.

Removing the `yaml` hash from `go.sum` has no effect on other dependencies.

**Comment by r2dedios** [comment]
I ask because I'm trying to update some features in cloud-prepare lib, and always I run `go mod vendor` I get that error. Thanks to you I understand why, but my questions was: Is this error an isolated one, or this fail could interrupt the `go mod vendor` command? Thanks

**Comment by skitt** [comment]
It stops the whole `go mod vendor` operation unfortunately. Could you try `GOPROXY=direct go mod vendor` instead?

**Comment by r2dedios** [comment]
Hi @skitt, sorry for the late response. 
No, anything changes. I only be able to update vendor folder using the Makefile.
I Think this could be related with my env too. I had several issues in other repos. 

Thanks for help! ;)

**Comment by skitt** [comment]
Ah, that suggests there’s something wrong in your local Go cache!

**Comment by r2dedios** [comment]
Looks like yes, I saw that mikefarah's lib its removed from the direct dependencies, but I still having errors with it.

**Comment by edennishri** [comment]
Thank you for the tag Mike, looking forward to learn the subject.

**Comment by MatanNahun** [comment]
Thank you Mike
