### ISSUE TITLE
Make golangci-lint leaves buildkitd container running

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#660]
Running `make golangci-lint` from a default Shipyard repo state results in a buildkitd container still running.

```
Successfully remade target file 'golangci-lint'.
[shipyard]$ make --debug=b golangci-lint
[~/go/src/submariner-io/shipyard]$ docker ps                                                                                         [devel]
CONTAINER ID   IMAGE                           COMMAND       CREATED        STATUS         PORTS     NAMES
fa0c03da140a   moby/buildkit:buildx-stable-1   "buildkitd"   21 hours ago   Up 2 minutes             buildx_buildkit_buildx_builder0
```

Note that the `golangci-lint` make target doesn't depend on the `clean-buildx` target, so this isn't the same as https://github.com/submariner-io/shipyard/issues/659.

**Comment by sridhargaddam** [comment]
@dfarrell07 I marked the priority as low as it's not affecting Submariner functionality and its like a stale resource running on the host. But feel free to modify the priority if required. Thank you.

**Comment by dfarrell07** [comment]
+1 to prio:low, this is more of an annoyance than a problem.

**Comment by dfarrell07** [comment]
This might go away as we change the underlying build infra.

**Comment by nyechiel** [comment]
@dfarrell07 is this still relevant?

**Comment by nyechiel** [comment]
@dfarrell07 ^^

**Comment by dfarrell07** [comment]
@nyechiel ACK

**Comment by dfarrell07** [comment]
Still seeing the same behavior with latest Shipyard after `make clean`/`make pune-images`.

```
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

$ git fetch
$ git reset --hard origin/devel
$ make golangci-lint
[21:09:18.546] [shipyard]$ make --debug=b golangci-lint
$ docker ps                                                                                         [devel]
CONTAINER ID   IMAGE                           COMMAND       CREATED       STATUS         PORTS     NAMES
84429d84c797   moby/buildkit:buildx-stable-1   "buildkitd"   4 weeks ago   Up 2 minutes             buildx_buildkit_buildx_builder0
```

**Comment by dfarrell07** [comment]
I don't think this needs to be done for 0.12.

**Comment by mkolesnik** [comment]
Doesn't reproduce for me, please reopen if still relevant with reproduction steps.
