### ISSUE TITLE
Make netperf image multi-arch

### ISSUE THREAD

**Issue by dberg1** [submariner-io/shipyard#696]
The quay.io/submariner/nettest image is only available for `amd64`.
I have installed submariner on a `ppc64le` OCP cluster and the `subctl diagnose` command fails because there is no nettest image for `ppc64le`.
Notice that building the nettest image for `ppc64le` requires some changes to the Dockerfile as this netperf patch:
https://github.com/HewlettPackard/netperf/commit/80bf19d563eebd1eca23f4092f96819296020fa5 has not made it into a tarball release.

```
# git diff
diff --git a/package/Dockerfile.nettest b/package/Dockerfile.nettest
index af7508d..29e7878 100644
--- a/package/Dockerfile.nettest
+++ b/package/Dockerfile.nettest
@@ -2,10 +2,10 @@ FROM alpine

 WORKDIR /app

-RUN apk add --update --no-cache gcc libc-dev make curl
+RUN apk add --update --no-cache gcc libc-dev make curl git automake autoconf

-RUN curl -L https://github.com/HewlettPackard/netperf/archive/netperf-2.7.0.tar.gz | tar xzf -
-RUN cd netperf-netperf-2.7.0 && ./configure CFLAGS=-fcommon \
+RUN git clone https://github.com/HewlettPackard/netperf
+RUN cd netperf && ./autogen.sh && ./configure CFLAGS=-fcommon \
     && make && make install
```

**Comment by skitt** [comment]
#697 doesn’t fix this entirely, some more steps are needed, but they are coming soon: see https://quay.io/repository/skitt/nettest for a multiarch image ;-).

**Comment by nyechiel** [comment]
The corresponding PR is already tracked in the 0.12 project board. No need to include both.
