### ISSUE TITLE
Weave images are always downloaded from Docker causing Docker Pull Rate error

### ISSUE THREAD

**Issue by Billy99** [submariner-io/shipyard#699]
Testing Submariner with generic `make deploy` from a server on corporate network and keep getting the Docker Pull Rate error on Weave Image:
```
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit.
  You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. 
```
Weave is downloaded to host, but clusters in KIND deployment don't have access to it and are attempting to re-download it.

**Comment by skitt** [comment]
One way to improve the situation would be to change the Weave deployment to look for images in the local repository, and push the images there.

Weave is deployed in `deploy_weave_cni` in `scripts/shared/clusters.sh`. This already tweaks the deployed image references; the idea here would be to extract the image references instead, pull them, push them to the local repository, and change the references in the Kubernetes manifest to point to the local repository. The local registry runs on `localhost:5000`; see `deploy_kind_ovn` for an example of its use.
