### ISSUE TITLE
Get `make backport` working in the dev container

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/shipyard#702]
Following https://github.com/submariner-io/shipyard/pull/692, a backport target needs to be used with `LOCAL_BUILD=1`.  ~~Use local build for default for `make backport` target.~~ Get it working in the dev container, following other examples.

**Comment by mkolesnik** [comment]
Alternative is to allow for it to run inside the containerized build env.

The benefit of that is not needing all the other stuff (`gh` etc) since its already available there.

I don't think that forcing it to always run outside is necessarily beneficial.

**Comment by dfarrell07** [comment]
Discussing on the PR Scrub, it does seem to make sense to get `mack backport` runable in the dev container. Adjusting title accordingly.

**Comment by dfarrell07** [comment]
The Scrub thinks this is working fine for us as-is, it's not a problem to add the extra arg.
