### ISSUE TITLE
Add linting for mixed tabs/spaces in shell scripts

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#731]
We currently have a gap in our linting that allows mixed tabs and spaces in shell scripts (at least). 

We should avoid mixed tabs and spaces for consistency and avoiding bugs.

We currently mostly (at least) use spaces. The easiest answer might just be failing on hard tabs in *.sh files. We could extend that to other types of files if we check and find other gaps (.md?).

**Comment by mkolesnik** [comment]
This can be interesting but two questions:
1. Does `shellcheck` support it?
2. Doesn't `markdownlint` check for no tabs?

For the first I found this open issue, which seems to imply there isnt a check for tabs (nor is there consensus which to use) - https://github.com/koalaman/shellcheck/issues/1659
It seems though that if we need this in shellcheck it would make sense to contribute it there directly

**Comment by dfarrell07** [comment]
Ran into this again, quite annoying gap in linting. I chimed in on the upstream issue noting that I think there may be consensus that mixed tabs and spaces are not good.
