### ISSUE TITLE
Run subctl gather in post mortem

### ISSUE THREAD

**Issue by vthapar** [submariner-io/shipyard#764]
Use `subctl gather` to collect data in post-mortem instead of custom scripts. This will also allow us to test `subctl gather` in our CI/CD.

Relates-to: https://github.com/submariner-io/enhancements/issues/88

Depends On: submariner-io/subctl#35

**Comment by dfarrell07** [comment]
There's an open question here about where to put the data, the tarballs subctl gather produces, so we can fetch them after.

**Comment by dfarrell07** [comment]
This was done in https://github.com/submariner-io/shipyard/pull/1233
