### ISSUE TITLE
Procedure for customizing Submariner clusters does not work

### ISSUE THREAD

**Issue by srampal** [submariner-io/shipyard#766]
I wanted to build a Kind based Submariner setup with changes to the cluster config (such as having clusters with 1 worker node each  instead of21 each).  I used the following make command .. (from within the submariner-operator repo)

make clusters CLUSTERS_ARGS='--settings ./testsettings.yaml'

and configured testsettings.yaml as suggested here ... https://submariner.io/development/shipyard/advanced/#deployment-scripts-features

However it still built the Kind clusters based on normal default settings and not the settings in the specified file.  Do I need to follow a different procedure ? (such as rebuild within the shipyard repo first before building in submariner-operator ?) Wasnt clear from the docs. Or is this a bug ? And if so, is there a workaround for now ?

**Comment by dfarrell07** [comment]
@mkolesnik thinks this has been fixed by moving to env vars, but we should check.

**Comment by mkolesnik** [comment]
Please check using `make clusters SETTINGS='./testsettings.yaml'`
