### ISSUE TITLE
Races between jobs in CI when deploying subctl

### ISSUE THREAD

**Issue by skitt** [submariner-io/shipyard#770]
Various CI jobs try to download `subctl`, and this can fail when a release job is updating the corresponding download artifacts; see https://github.com/submariner-io/shipyard/runs/5788292368?check_suite_focus=true for example.

We might want to consider either retrying downloads, or using a lock so that jobs requiring `subctl` wouldn’t run while a conflicting release job is running (but as far as I can tell that would involve serialising _all_ such jobs).

**Comment by dfarrell07** [comment]
```
Downloading...
curl: (22) The requested URL returned error: 404
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[13:17:09.636] [shipyard]$ [cluster2] bash -c curl -Ls https://get.submariner.io | VERSION=devel DESTDIR=/go/bin bash
Installing subctl version devel
  OS detected:           linux
  Architecture detected: amd64
  Download URL:          https://github.com/submariner-io/submariner-operator/releases/download/subctl-devel/subctl-devel-linux-amd64.tar.xz

Downloading...
curl: (22) The requested URL returned error: 404
```

**Comment by skitt** [comment]
We now retry the downloads (see https://github.com/submariner-io/shipyard/pull/893).
