### ISSUE TITLE
Multi arch images release broke the CI

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#771]
I noticed CI started failing with this error:
```
  error: failed to solve: failed to get reader: content digest sha256:40e059520d199e1a1a259089077f2a0c879951c9a4540490bad3a0d7714c6ae7: not found
```

This seems to be related to the latest merge which published multi arch images.

We're either not consuming them correctly or not publishing them correctly (e.g. should have a default platform?).

For example, see https://github.com/submariner-io/shipyard/runs/5805414807?check_suite_focus=true

**Comment by skitt** [comment]
I’ve moved `nettest:devel` back to `nettest:devel-8cbbe6c`, the last non-multi-arch tag, and re-run the failed jobs to check.
