### ISSUE TITLE
Support running containers using Podman 

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#778]
The [Docker daemon adds a security surface](https://docs.docker.com/engine/security/#docker-daemon-attack-surface) and (for me at least) is very flaky compared to Podman. Shipyard should support running containers using Podman under the hood.

Note that [building containers without Docker using Buildah is related but different from running containers without Docker using Podman](https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users#container_images_are_compatible_between_podman_and_other_runtimes).

```
[~/go/src/submariner-io/shipyard]$ grep -rni --exclude-dir=vendor docker | wc -l
153
```

**Comment by skitt** [comment]
Our `.dapper` implementation already supports running with Podman, at least with the `podman-docker` setup (where Podman provides a `docker` tool which uses Podman). Some scenarios rely on a user-private Podman service, which can be enabled with `systemctl --user --now enable podman.socket`; this will ensure that the service is started as necessary.

The major limitation right now is that our kind setup doesn’t work well on Podman.

**Comment by maayanf24** [comment]
@dfarrell07 - Is this still relevant?
