### ISSUE TITLE
Stop using Weave

### ISSUE THREAD

**Issue by skitt** [submariner-io/shipyard#858]
Weave is largely unsupported upstream, and it’s not clear we actually _need_ it specifically; we initially added Weave so that we could work on network policy support.

We should look at the current CNI space, in particular kind-friendly CNIs, and switch to whatever seems most appropriate.

**Comment by mkolesnik** [comment]
How about just using the default kindnet for now?

IDK if we have any deficiencies with it, but if Weave is unsupported then using the default would be our best bet until we hit something it doesn't provide.

**Comment by sridhargaddam** [comment]
When deployed with default (aka kindnet), subctl CNI detection reports the CNI as "generic" but all the test-cases are passing fine. We can enhance the CNI detection code to detect and report the CNI in a future PR.
