### ISSUE TITLE
Set SONAR_TOKEN variable in "Secrets" settings of repos

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#871]
I need a Submariner admin to [create a SonarCloud token](https://sonarcloud.io/account/security/) and [add it as the environment variable `SONAR_TOKEN`](https://github.com/SonarSource/sonarcloud-github-action#secrets) to repos that run Go unit tests.

This is a part of https://github.com/stolostron/backlog/issues/22706.

**Comment by skitt** [comment]
This is done.
