### ISSUE TITLE
Fix new gosec G112 Potential Slowloris Attack issues

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#900]
While updating golangci-lint (https://github.com/submariner-io/shipyard/pull/899), we're seeing new gosec failures in various projects.

> Consuming Projects / Lint (coastguard)

```
pkg/healthz/healthz.go:36:16: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
		httpServer: &http.Server{Addr: address},
		             ^
```

Depends on https://github.com/submariner-io/coastguard/pull/72

> Consuming Projects / Lint (lighthouse)

```
pkg/agent/main.go:151:10: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
	srv := &http.Server{Addr: ":8082"}
```

Depends on https://github.com/submariner-io/lighthouse/pull/845

> Consuming Projects / Lint (submariner)

```
pkg/globalnet/main.go:145:10: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
	srv := &http.Server{Addr: ":8081"}
	        ^
main.go:321:10: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
	srv := &http.Server{Addr: ":8080"}
	        ^
```

Depends on https://github.com/submariner-io/submariner/pull/1948

**Comment by dfarrell07** [comment]
Interesting context: https://medium.com/a-journey-with-go/go-understand-and-mitigate-slowloris-attack-711c1b1403f6

**Comment by dfarrell07** [comment]
There's very little information out there about error. The [golangci-lint PR](https://github.com/securego/gosec/pull/809)/[golangci-lint Issue](https://github.com/securego/gosec/issues/807) linked to the same blog post as above for justification/explanation. There's also [recent discussion about `ReadTimeout` being used if `ReadHeaderTimeout` isn't set](https://github.com/securego/gosec/issues/807#issuecomment-1191843244).

**Comment by dfarrell07** [comment]
This blog is the the most recent/relevant docs about proper Go net/http timeouts I've been able to find: https://ieftimov.com/posts/make-resilient-golang-net-http-servers-using-timeouts-deadlines-context-cancellation/

Seems like there's a lot to consider, I'm not sure it's as simple as adding a `ReadHeaderTimeout`. Any guidance @tpantelis @skitt @sridhargaddam?

**Comment by tpantelis** [comment]
> Seems like there's a lot to consider, I'm not sure it's as simple as adding a ReadHeaderTimeout. Any guidance @tpantelis

Discussing on slack, I think we should start by addressing this specific security issue and let the tooling inform us going forward. Perhaps we can optimize performance by following the guidance in that article you posted but it's unclear what usage patterns these http servers will experience to warrant possible premature optimization. That's my take.
