### ISSUE TITLE
Test day tooling (OpenShift)

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#913]
We're having regular test days but the process of standing up clusters for testing is manual (except KIND based), it could be beneficial to develop some automated tooling (eg some scripts or a binary) that will do a lot of the manual work for standing up the clusters.

E.G. to stand up a test env on AWS one needs to:
1. Deploy a couple of clusters on AWS, using the desired OpenShift version
2. Alter kubeconfigs for properly working with multiple clusters
3. Prepare the cloud for submariner deployment
4. Deploy submariner properly (e.g. globalnet if clusters were deployed with overlapping IPs, specific cable driver is needed)
5. Run `subctl verify`
6. Open an issue labeled with the testday label with `subctl gather` output in case of fasilure (of the verify or manual testing)

Seems like most of these steps can be rather easily automated in one or a few commands which will reduce user-errors and streamline test days. It also seems that these steps will be rather similar for different clouds when deploying with OpenShift.
This might also ease the testing process, thus encouraging participation in the test days.

**Comment by skitt** [comment]
I use the following Makefile to deploy on AWS, run cloud-prepare, and fix up the kubeconfigs:

```make
deploy:
	for c in h 1 2; do \
		if [ ! -d awsocp$${c} ]; then \
			cp -a awsocp$${c}-template awsocp$${c}; \
			openshift-install create cluster --dir=awsocp$${c} > awsocp$${c}.log 2>&1 & \
		fi; \
	done
	tail -f awsocp?.log

cloud-prepare:
	for c in h 1 2; do \
		KUBECONFIG=awsocp$${c}/auth/kubeconfig subctl cloud prepare aws --ocp-metadata awsocp$${c}/metadata.json; \
	done

kubeconfig:
	for c in h 1 2; do \
		yq -i '.contexts[0].context.user = "admin-'$$c'" | .contexts[0].name = "admin-'$$c'" | .users[0].name = "admin-'$$c'" | .current-context = "admin-'$$c'"' awsocp$${c}/auth/kubeconfig; \
	done

clean:
	for c in h 1 2; do \
		[ -f awsocp$${c}/metadata.json ] && openshift-install destroy cluster --dir=awsocp$${c}; \
	done
	rm -rf awsocp?
```

**Comment by mkolesnik** [comment]
@skitt it actually makes sense to keep in Shipyard, any reason you reopend it here?

**Comment by skitt** [comment]
On Wed, Aug 10, 2022 at 02:47:04AM -0700, Mike Kolesnik wrote:
> @skitt it actually makes sense to keep in Shipyard, any reason you reopend it here?

So that I could transfer it properly to Shipyard.

**Comment by mkolesnik** [comment]
> So that I could transfer it properly to Shipyard.

It all was very confusing as I saw this on the original issue or `releases` :man_shrugging:
