### ISSUE TITLE
Add K8s 1.25 to CI

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/shipyard#949]
K8s 1.25 is out and we should test it in CI as the default K8s version.

Depends on https://github.com/submariner-io/shipyard/pull/950
Depends on https://github.com/submariner-io/shipyard/pull/951
Depends on https://github.com/submariner-io/submariner-operator/pull/2247
Depends on https://github.com/submariner-io/lighthouse/pull/882
Depends on https://github.com/submariner-io/submariner-charts/pull/269

**Comment by nyechiel** [comment]
@dfarrell07 with both https://github.com/submariner-io/shipyard/pull/951 and https://github.com/submariner-io/shipyard/pull/950 merged, what else is required?

**Comment by skitt** [comment]
This has been implemented across all repositories, thanks @dfarrell07!
